### ISSUE TITLE
Bug: The Panel component introduces a horizontal scrollbar

### ISSUE THREAD

**Issue by anevins12** [sky-uk/toolkit-ui#207] opened 2017-01-17 09:50 UTC
The panel component produces a scrollbar when it is used full-width.

## Expected Behavior
When the panel component is implemented full-width, from one side of the screen to the other, I expect the component to behave as it does in the Sky toolkit.

## Current Behavior
When the panel component is implemented full-width, from one side of the screen to the other, a horizontal scrollbar appears and persists at many resolutions.
![panel-bug](https://cloud.githubusercontent.com/assets/2318561/22015515/538e40f6-dc9a-11e6-812f-ad62acfff967.png)

**Comment by joebell93** [comment] 2017-01-17 09:53
@anevins12 please can you provide more detail?

- What version of Toolkit are you using?
- What markup are you using?
- What have you tried doing to resolve this?

**Comment by anevins12** [comment] 2017-01-17 10:09
**Toolkit version: 1.0.2** - However the issue persists on the Sky.com/toolkit website when moving the component outside of its container.
**Markup:**
`
<article class="c-panel is-open c-panel--dark">
    
</article>
`
I have tried reducing the 'width: 100vw' style and using a pseudo element of ':before' to make up the remainder width, but this cannot work while the panel has an overflow of hidden.

**Comment by StefanMcCready** [comment] 2017-01-17 10:20
@anevins12 You may want to think about moving to Toolkit 1.5.0, 1.0.2 is a fairly old version of the toolkit now

**Comment by anevins12** [comment] 2017-01-17 10:21
Noted. Which version is released to Sky.com/toolkit?

**Comment by joebell93** [comment] 2017-01-17 10:21
@anevins12 interesting, if this on sky.com/toolkit then this is the latest version too. I'll take a look

**Comment by StefanMcCready** [comment] 2017-01-17 10:24
@anevins12 sky.com/toolkit is on 1.4.0

**Comment by anevins12** [comment] 2017-02-17 10:02
Hi @joebell93, Have you had time to look into this?

**Comment by joebell93** [comment] 2017-02-17 10:35
@anevins12 I've still yet to see this in the current version of Toolkit, did you upgrade to the latest version?

Also just a side-note, Toolkit is very much open-source project and we welcome any contributions to it

**Comment by anevins12** [comment] 2017-02-17 10:47
This can be replicated by using the panel component outside of any grid layouts. For example the HTML could be::
`
<body>
<article class="c-panel c-panel--width-constraint is-open">
`
Can you double-check that you're not able to replicate?

**Comment by joebell93** [comment] 2017-02-17 11:30
I'm afraid I'm not going to have any time soon to replicate this in the near future - if you solve this please feel free to contribute back into Toolkit

**Comment by anevins12** [comment] 2017-02-20 12:04
Our resolution to this was to change the following.
From:
```
.c-panel {
 ...
  margin-left: -50vw;
  position: relative;
  width: 100vw;
```
To:
.c-panel {
 ...
  margin-left: -50%;
  position: absolute;
  width: 100%;
}
```
Which then caused us to use JavaScript to add the height of the panel. Not a proud solution, but thought I'd let you know. 

All the best.

**Comment by joebell93** [comment] 2017-03-02 15:39
@anevins12 I've tried using this outside of the grid but I don't seem to be suffering the same problem as you, are you definitely on the latest version / sure it isn't conflicting project CSS?

**Comment by anevins12** [comment] 2017-03-02 15:45
Yes I was confirming the issue via the Sky.com/toolkit using a browser developer toolbar. 
I've created a jsFiddle to demonstrate that it's not related to project-specific CSS: https://fiddle.jshell.net/hqqj7bzb/show/

The CSS used in that jsFiddle demo is taken directly from this URL: https://www.sky.com/watch/assets/6ca412adda14237001c9.core.css

**Comment by anevins12** [comment] 2017-03-02 15:47
I noticed that the issue may only be visible at certain browser sizes. Can you replicate the issue on that jsFiddle in Chrome, newest, by arbitrarily resizing the browser down to sizes smaller than desktop?

**Comment by joebell93** [comment] 2017-03-03 09:33
@anevins12 I can't seem to replicate this in Chrome Version 56.0.2924.87 (64-bit) for Mac - your examples looks fine to me!

Also, not sure if it was only for that demo, but you should absolutely **not** be using that CSS file from `watch/assets/` in production.
That is not the Toolkit, it's a project-specific implementation and will contain various hacks/overrides that update regularly with no warning

You should **only** use [SCSS via the NPM package](https://github.com/sky-uk/toolkit#installation), or [pre-compiled CSS via `assets`](https://github.com/sky-uk/toolkit#compiled) via our `assets/` ✈️

**Comment by anevins12** [comment] 2017-03-03 09:49
Thanks for checking. I should mention I'm on Windows 7, Chrome Version 56.0.2924.87.
I've also noticed that the issue disappears on some page refreshes.

Yes, not to worry that CSS used in the jsFiddle example was only to demonstrate the issue and we are not using it in production. We have been using SCSS via the NPM project.

I have added a short video file demonstrating the intermittent issue: https://drive.google.com/file/d/0B-_GK4LwVcWHaUtnTkVuLVNCa3c/view

**Comment by joebell93** [comment] 2017-03-03 10:02
Right ok, I'll see if I can get someone to test this and check

Phew, panic over. Glad to hear you're using the NPM package.

Appreciate you taking the time to do a video, that's a strange bug. It almost seems to be affected by the vertical scrollbar?

**Comment by anevins12** [comment] 2017-03-03 10:07
Great thanks! Yes I was thinking that the 'vw' measurement isn't always correctly calculated by the browser in relation to the scrollbar. I haven't investigated this though. 

This issue was failing our internal QA process, but I've resolved it using the above method. So it's not an urgent issue from our end, but may still be useful to resolve.

**Comment by anevins12** [comment] 2017-03-03 10:51
I just checked caniuse.com for known issues and this appears to be a known issue:

> Currently all browsers but Firefox incorrectly consider 100vw to be the entire page width, including vertical scroll bar, which can cause a horizontal scroll bar when overflow: auto is set.
http://caniuse.com/#search=viewport%20w

**Comment by JamieMason** [comment] 2017-05-11 09:35
Incase it's useful to anyone, me and @aaronthomas have have found the following steps to reproduce this issue;

1. Open "System Preferences > General" on your Mac.
1. Choose "Show scroll bars > Always".
1. Visit http://www.sky.com/blackjack/toolkit/components/panel
1. Open Devtools and run this in the console `document.body.appendChild(document.querySelector('.c-panel.c-panel--width-constraint.is-open'))`.
1. Scroll down and the panel example will be at the bottom of the page, full width.
1. You should now see the horizontal scrollbar.

For Mac users, having scroll bars always shown should be enough to help reproduce it. Windows etc users will always have scroll bars anyway, so it would be easier to reproduce.

**Comment by JamieMason** [comment] 2017-05-11 09:53
We have an idea to put forward for discussion, which is to add the following to toolkit-core;

```css
html,
body {
  overflow-x: hidden;
}
```

Trade-offs

✘ Seems like a hack.
✓ Fixes the problem.
✓ Doesn't require JavaScript.
✘ Horizontal scrolling of the body would not be possible on any sky product.
✓ When have you ever seen horizontal scrolling on the body of any sky product?
✓ Horizontal scrolling could still be achieved with a scrolling element nested in the body.
✓ Other possible fixes we've considered have seemed even hackier.
... any others?

Resources

https://cloudfour.com/thinks/breaking-out-with-viewport-units-and-calc/

**Comment by StefanMcCready** [comment] 2017-05-11 12:36
Its interesting, I had seen this problem on mobile and thought the above solution shown would actually be the simplest way to fix it all things considered.

**Comment by joebell93** [comment] 2017-05-30 09:06
@JamieMason personally I think this is a valid solution, and like you said, when have we ever seen horizontal scrolling on a Sky product?
This _could_ always be overridden if absolutely necessary 

Let's get this in as an `_overflow.scss` layer of our *Generic* styles in toolkit-core

cc/ @sky-uk/toolkit thoughts?

**Comment by joebell93** [comment] 2017-06-01 14:43
@JamieMason just tried here, no luck 😢 
http://tv.sky.com/tv-guide/

**Comment by joebell93** [comment] 2017-06-02 09:59
@JamieMason very good point, sounds like a utility class would be best for this. Just need to make sure it's well documented 

@LucaColonnello @maheshjag I'm going to suggest we override this in the defence for the new masthead to avoid conflicts with apps like the TV guide

**Comment by joebell93** [comment] 2017-06-02 12:13
Moved to https://github.com/sky-uk/toolkit/issues/231

**Closed by joebell93** 2017-06-02 12:13 UTC
Labels: bug

**Comment by colingourlay** [comment] 2017-06-02 14:36
Hey folks, if you're not worried about browsers that don't support CSS custom properties (Internet Explorer), I've just finished building a solution that might work for you. I've turned `document.documentElement.clientWidth` into a usable unit in CSS: https://github.com/colingourlay/root-units
